### ISSUE TITLE
Uncaught TypeError: Cannot read property 'bool' of undefined

### ISSUE THREAD

**Issue by jtan4nih** [sdgluck/react-z-index#1]
We tried to use this component as such:

import ZIndex from 'react-z-index' // component, util
// import { zIndex } from 'react-z-index' // decorator
// Inform lib of the value so we can pick it up 
// elsewhere in the app as ZIndex.vars.Modal
const zIndex = ZIndex.setVar('Modal', 100)

...
      <ReactJsSearchBox className='modal' style={{ zIndex }} ref={ref => this.reactJsSearchBox = ref}
        options={{
                    label: <Icon icon={search}/>,
                    placeHolder: 'Search'
                }}
        style={{padding: 5, float: 'right', height: '50px', width: '95%', background: '#D3D3D3'}} onChange={this.onChange} onKeyDown={this.search} 
        live={false}
        datas={this.state.dataList}
        api={{
            url: '',
            method: 'GET'
        }}
        action={{
            selectItem: this.selectItem
        }}
      />

But we got the error as show in the subject. Please advise what we are missing? Thanks!

**Comment by sdgluck** [comment]
@jtan4nih Please can you share the stack trace of the error, as this will help locate the problem.

**Comment by dwaps** [comment]
![image](https://user-images.githubusercontent.com/9659087/50792404-262f4480-12c5-11e9-8889-2c6e91a70c0d.png)

**Comment by sdgluck** [comment]
Thanks @dwaps. I'll try find some time to look at this soon, along with ensuring compat. with React 16.

**Comment by dwaps** [comment]
Thank you so much. Have a good day ! :)

**Comment by sdgluck** [comment]
Fixed on latest (`react-z-index@3.0.0`). Thanks
